### ISSUE TITLE
Frame doesnt know I'm using a UK keyboard so certain characters are typed wrongly in Firestorm

### ISSUE THREAD

**Issue by Whirly-Fizzle** [BrightCanopy/BrightCanopy.github.io#6]
I'm in the UK, so using a UK keyboard.
When I type certain characters in Firestorm, they give the output from a foreign  keyboard layout - I havn't worked out which keyboard yet, doesn't appear to be American.

For example:
- If I type @ into chat, I actually type "
- If I type # into chat, nothing is entered
- If I type ¬ into chat, I actually type ~

**Comment by BrightCanopy** [comment]
This should be fixed in our environment now. Please retest and reopen if you see any other UK keyboard issues.

> Hi Bill,
> 
> We've got that part covered with a beta feature that automatically detects the language/keyboard
> layout. I've just turned it on for the account you're using (sl@fra.me) - you'll see it show up as a
> language indicator in the status bar at the bottom of the player (for me it shows as "ENG").
> 
> thanks,
> Carsten
> 
> Frame Support

**Comment by InaraPey** [comment]
UK keyboard input still not recognised. 

Frame reports "ENG" as selected language, but UK keyboards map to US English keyboard layout. 

As Whirly reports:

Pressing the @  key on a UK keyboard causes " to be typed.
Whereas pressing the " key (SHIFT-2 on a UK keyboard layout) causes @ to be typed.
Etc.

**Comment by BrightCanopy** [comment]
Reopening. I've contacted Frame Support with the update.

**Comment by BrightCanopy** [comment]
You may now select the UK keyboard from the "ENG" button on the bottom right of the frame.
